#cloud-config
#
# This is an cloud-init file to download and install the azcmagent.
#
# Don't create files in /tmp during the early stages that cloud-init works in. Use /var/run.
# Generated runcmd script run as root: sudo cat /var/lib/cloud/instance/scripts/runcmd
# Cloud-init output: cat /var/log/cloud-init-output.log

merge_how:
 - name: list
   settings: [append]
 - name: dict
   settings: [no_replace, recurse_list]

cloud_config_modules:
  - runcmd
cloud_final_modules:
  - scripts-user

runcmd:
 - echo "Starting azcmagent install runcmd steps at $(date +%H:%M:%S)"
 - wget --no-verbose https://aka.ms/azcmagent -O /var/run/install_linux_azcmagent.sh
 - chmod 755 /var/run/install_linux_azcmagent.sh
 - bash /var/run/install_linux_azcmagent.sh
 - echo "Finished azcmagent install runcmd steps at $(date +%H:%M:%S)"
